require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreferencesController do

  # This should return the minimal set of attributes required to create a valid
  # BookPreference. As you add validations to BookPreference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookPreferencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET show" do
    it "assigns the requested book_preference as @book_preference" do
      book_preference = OptedOut.create! valid_attributes
      get :show, {:id => book_preference.to_param}, valid_session
      assigns(:book_preference).should eq(book_preference)
    end
  end

  describe "GET new" do
    it "assigns a new book_preference as @book_preference" do
      get :new, {}, valid_session
      assigns(:book_preference).should be_a_new(BookPreference)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_preference as @book_preference" do
      book_preference = OptedOut.create! valid_attributes
      get :edit, {:id => book_preference.to_param}, valid_session
      assigns(:book_preference).should eq(book_preference)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookPreference" do
        expect {
          post :create, {:book_preference => valid_attributes}, valid_session
        }.to change(BookPreference, :count).by(1)
      end

      it "assigns a newly created book_preference as @book_preference" do
        post :create, {:book_preference => valid_attributes}, valid_session
        assigns(:book_preference).should be_a(BookPreference)
        assigns(:book_preference).should be_persisted
      end

      it "redirects to the created book_preference" do
        post :create, {:book_preference => valid_attributes}, valid_session
        response.should redirect_to(OptedOut.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_preference as @book_preference" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptedOut.any_instance.stub(:save).and_return(false)
        post :create, {:book_preference => {  }}, valid_session
        assigns(:book_preference).should be_a_new(BookPreference)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptedOut.any_instance.stub(:save).and_return(false)
        post :create, {:book_preference => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_preference" do
        book_preference = OptedOut.create! valid_attributes
        # Assuming there are no other book_preferences in the database, this
        # specifies that the BookPreference created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OptedOut.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => book_preference.to_param, :book_preference => { "these" => "params" }}, valid_session
      end

      it "assigns the requested book_preference as @book_preference" do
        book_preference = OptedOut.create! valid_attributes
        put :update, {:id => book_preference.to_param, :book_preference => valid_attributes}, valid_session
        assigns(:book_preference).should eq(book_preference)
      end

      it "redirects to the book_preference" do
        book_preference = OptedOut.create! valid_attributes
        put :update, {:id => book_preference.to_param, :book_preference => valid_attributes}, valid_session
        response.should redirect_to(book_preference)
      end
    end

    describe "with invalid params" do
      it "assigns the book_preference as @book_preference" do
        book_preference = OptedOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptedOut.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_preference.to_param, :book_preference => {  }}, valid_session
        assigns(:book_preference).should eq(book_preference)
      end

      it "re-renders the 'edit' template" do
        book_preference = OptedOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptedOut.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_preference.to_param, :book_preference => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_preference" do
      book_preference = OptedOut.create! valid_attributes
      expect {
        delete :destroy, {:id => book_preference.to_param}, valid_session
      }.to change(BookPreference, :count).by(-1)
    end

    it "redirects to the book_preferences list" do
      book_preference = OptedOut.create! valid_attributes
      delete :destroy, {:id => book_preference.to_param}, valid_session
      response.should redirect_to(book_preferences_url)
    end
  end

end
